# Generated by Django 5.0.3 on 2024-03-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('resume', models.TextField(verbose_name='Resumen')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.servicestatus'),
        ),
    ]
