# Generated by Django 5.0.2 on 2024-03-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='service',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='servicestatus',
            name='last_update',
        ),
    ]
