# Generated by Django 5.0.2 on 2024-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_incidence_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
