# Generated by Django 5.0.2 on 2024-03-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_service_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='last_updated',
        ),
    ]
